version: 0.2
 
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "🔧 Installing dependencies"
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pylint pytest pytest-django
 
  pre_build:
    commands:
      - echo "📦 Checking Python version"
      - python --version
 
      - echo "🔍 Running pylint on ebookstore/"
      - pylint --exit-zero $CODEBUILD_SRC_DIR/ebookstore/*.py
 
      - echo "🔍 Running pylint on books/"
      - pylint --exit-zero $CODEBUILD_SRC_DIR/books/*.py
 
  build:
    commands:
      - echo "🧪 Running pytest for all tests"
      - pytest || true  # Use `|| true` only if you want to avoid breaking the build on test failures
 
artifacts:
  files:
    - '**/*'