version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "🔧 Installing system packages"
      - yum install -y wget unzip jq python3-virtualenv

      - echo "🐍 Configuring Python environment"
      - python3 -m venv venv
      - source venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt

      - echo "⬇ Installing Sonar Scanner"
      - wget -q https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip -q sonar-scanner-cli-5.0.1.3006-linux.zip
      - chmod +x sonar-scanner-5.0.1.3006-linux/bin/*
      - export SONAR_SCANNER_PATH="$PWD/sonar-scanner-5.0.1.3006-linux/bin"
      - echo "PATH=$PATH:$SONAR_SCANNER_PATH" >> $CODEBUILD_SRC_DIR/.env

  build:
    commands:
      - source venv/bin/activate
      - source $CODEBUILD_SRC_DIR/.env
      
      - echo "🧪 Running Django tests"
      - python manage.py test

      - echo "📊 Running SonarQube scan"
      - >
        sonar-scanner
        -Dsonar.projectKey=$SONAR_PROJECT_KEY
        -Dsonar.organization=$SONAR_ORG
        -Dsonar.sources=.
        -Dsonar.host.url=$SONAR_HOST
        -Dsonar.login=$SONAR_TOKEN
        -Dsonar.python.version=3.11

cache:
  paths:
    - venv/**/*
    - sonar-scanner-*/**/*
