version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      # Install dependencies needed for running the static analysis
      - pip install -r requirements.txt
  pre_build:
    commands:
      - python --version
      - export DJANGO_SETTINGS_MODULE=ebookstore.settings
      - pylint --load-plugins pylint_django $CODEBUILD_SRC_DIR/ebookstore/

# Optional artifacts section (if needed)
artifacts:
  files:
    - '**/*'
